// <auto-generated />
using System;
using GoalLine.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalLine.DataAccess.Migrations
{
    [DbContext(typeof(LeagueDbContext))]
    [Migration("20241018152002_AddedLeagueAndMatch")]
    partial class AddedLeagueAndMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GoalLine.Domain.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("GoalLine.Domain.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("GoalLine.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("CountOfAwayTeamGoals")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("CountOfHomeTeamGoals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GoalLine.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3717),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Persepolis"
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3720),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Esteghlal F.C."
                        },
                        new
                        {
                            Id = 3,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3721),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Malavan"
                        },
                        new
                        {
                            Id = 4,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3722),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tractor"
                        },
                        new
                        {
                            Id = 5,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3723),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sepahan"
                        },
                        new
                        {
                            Id = 6,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3724),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Foolad"
                        },
                        new
                        {
                            Id = 7,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3725),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gol Gohar"
                        },
                        new
                        {
                            Id = 8,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3726),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chadormalu"
                        },
                        new
                        {
                            Id = 9,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3727),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Zob Ahan"
                        },
                        new
                        {
                            Id = 10,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3808),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Esteghlal Khuzestan"
                        },
                        new
                        {
                            Id = 11,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3809),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Aluminium Arak"
                        },
                        new
                        {
                            Id = 12,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3810),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mes Rafsanjan"
                        },
                        new
                        {
                            Id = 13,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3811),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kheybar"
                        },
                        new
                        {
                            Id = 14,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3812),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nassaji Mazandaran"
                        },
                        new
                        {
                            Id = 15,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3813),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shams Azar"
                        },
                        new
                        {
                            Id = 16,
                            CoachId = 0,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 20, 1, 388, DateTimeKind.Utc).AddTicks(3814),
                            LeagueId = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Havadar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
