// <auto-generated />
using System;
using GoalLine.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalLine.DataAccess.Migrations
{
    [DbContext(typeof(LeagueDbContext))]
    partial class LeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GoalLine.Domain.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("GoalLine.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9884),
                            Title = "Persepolis"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9888),
                            Title = "Esteghlal F.C."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9890),
                            Title = "Malavan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9891),
                            Title = "Tractor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9892),
                            Title = "Sepahan"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9893),
                            Title = "Foolad"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9894),
                            Title = "Gol Gohar"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9895),
                            Title = "Chadormalu"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9896),
                            Title = "Zob Ahan"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9897),
                            Title = "Esteghlal Khuzestan"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9898),
                            Title = "Aluminium Arak"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9899),
                            Title = "Mes Rafsanjan"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9900),
                            Title = "Kheybar"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9901),
                            Title = "Nassaji Mazandaran"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9902),
                            Title = "Shams Azar"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 2, 18, 56, 9, 206, DateTimeKind.Utc).AddTicks(9903),
                            Title = "Havadar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
